unit TestUntCalculadora;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, Vcl.Graphics,
  System.Variants, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls, Vcl.Forms,
  UntCalculadora, System.Classes;

type
  // Test methods for class TFrmCalculadora

  TestTFrmCalculadora = class(TTestCase)
  strict private
    FFrmCalculadora: TFrmCalculadora;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestSomar;
    procedure TestSubtrair;
    procedure TestMultiplicar;
    procedure TestDividir;
  end;

implementation

procedure TestTFrmCalculadora.SetUp;
begin
  FFrmCalculadora := TFrmCalculadora.Create(nil);
end;

procedure TestTFrmCalculadora.TearDown;
begin
  FFrmCalculadora.Free;
  FFrmCalculadora := nil;
end;

procedure TestTFrmCalculadora.TestSomar;
var
  ReturnValue: Integer;
  Anumero2: Integer;
  ANumero1: Integer;
begin
  Anumero1 := 3;
  Anumero2 := 3;
  ReturnValue := FFrmCalculadora.Somar(ANumero1, Anumero2);
  CheckEquals(6,ReturnValue,'O teste da soma falhou');
end;

procedure TestTFrmCalculadora.TestSubtrair;
var
  ReturnValue: Integer;
  Anumero2: Integer;
  ANumero1: Integer;
begin
  Anumero1 := 3;
  Anumero2 := 3;
  ReturnValue := FFrmCalculadora.Subtrair(ANumero1, Anumero2);
  CheckEquals(5,ReturnValue,'O teste da Subtrair falhou');
end;

procedure TestTFrmCalculadora.TestMultiplicar;
var
  ReturnValue: Integer;
  Anumero2: Integer;
  ANumero1: Integer;
begin
  Anumero1 := 3;
  Anumero2 := 3;
  ReturnValue := FFrmCalculadora.Multiplicar(ANumero1, Anumero2);
  CheckEquals(9,ReturnValue,'O teste da Multiplicar falhou');
end;

procedure TestTFrmCalculadora.TestDividir;
var
  ReturnValue: Integer;
  Anumero2: Integer;
  ANumero1: Integer;
begin
  Anumero1 := 3;
  Anumero2 := 3;
  ReturnValue := FFrmCalculadora.Dividir(ANumero1, Anumero2);
  CheckEquals(1,ReturnValue,'O teste da Dividir falhou');
end;
initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFrmCalculadora.Suite);
end.

