name: Build

on:
  push:
    branches:
      - master
      - main
      - develop
      - 'feature/**'
      - 'bugfix/**'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: compile-project
        shell: powershell
        run: Unblock-File -Path .\compilador.bat
        run: .\compilador.bat

      - name: execute-test
        shell: powershell
        run: .\Test\Win32\Debug\PrjCalculadoraTests.exe